config/routes.rb
Haokaigan::Application.routes.draw do
  
  resources :discussions

  resources :logs

  resources :tools

  root :to => 'home#index'
  
  resources :notifications

  resources :users

  resources :sessions,      :only => [:index, :new, :create, :destroy]

  get 'establishes/add'
  get 'home/caiwu'
  
  resources :experiences

  resources :partners

  resources :tips

  resources :pages

  resources :notes

  resources :chapters

  resources :establishes
  
  
  
  match '/admin/kuang' => 'admin#kuang'
  match '/admin/index' => 'admin#index'
  match '/admin/chapter' => 'admin#chapter'
  match '/admin/note' => 'admin#note'
  match '/admin/index/new' => 'establishes#new'
  match '/signout' => 'sessions#destroy'
  match '/signin' => 'sessions#new'
  
  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :establish
  has_many   :note
  has_many   :tip
  has_many   :partner
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/establish.rb
class Establish < ActiveRecord::Base
  has_many :chapter
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :chapter
  has_many :log, :dependent => :destroy
  has_many :user, :through => :log

  has_many :discussion, :dependent => :destroy
  has_many :user, :through => :discussion
    
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :chapter
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/setting.yml"
  namespace Rails.env
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :chapter
end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :notification, :dependent => :destroy
  has_many :log, :dependent => :destroy
  has_many :discussion, :dependent => :destroy


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password


  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate_name(name, submitted_password)
      user = find_by_name(name)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_email(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
  
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end


  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all


    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  # GET /discussions/new.json
  def new
    @discussion = Discussion.new
    if !params[:establish].nil?
    @note = Establish.find(params[:establish]).chapter.find(params[:chapter]).note.find(params[:note])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(params[:discussion])

    respond_to do |format|
      if @discussion.save
        @log = Log.create(:l_type => 'Add discussion',:content => @discussion.content, :user_id => current_user.id , :note_id => @discussion.note.id)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render json: @discussion, status: :created, location: @discussion }
      else
        format.html { render action: "new" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discussions/1
  # PUT /discussions/1.json
  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discussions/_content.html.erb
<% floor = 0  %>
<% @note.discussion.each do |discussion| %>
<div class="discussion_windows" id="discussion_window_<%= @note.id %>">
#<%= floor += 1  %></br>
<%= discussion.content %></br>
<%= image_tag '/images/user.png' %> <%= discussion.user.name %> <%= image_tag '/images/clock.png' %> <%= discussion.created_at.to_date %>
</br>
</div>
<% end %>

<div class="discussion_windows" id="discussion_window_<%= @note.id %>">
<%= form_for(@discussion) do |f| %>

  <div class="field">
    <%= f.text_field :note_id,:value => params[:note] %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id,:value => current_user.id %>
  </div>
  <div class="field">
    <%= f.text_area :content,:rows => 3,:width => '600px' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/discussions/_form.html.erb
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note_id %><br />
    <%= f.number_field :note_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <tr>
    <th>Note</th>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @discussions.each do |discussion| %>
  <tr>
    <td><%= discussion.note_id %></td>
    <td><%= discussion.user_id %></td>
    <td><%= discussion.content %></td>
    <td><%= link_to 'Show', discussion %></td>
    <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
    <td><%= link_to 'Destroy', discussion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= render 'shared/discussions' %>
<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/new.js.erb
$("[id^=add_discussion_]").click(function (){
	$(".discussion_windows").remove();
});

$("#edit_window_<%= @note.id %>").html("<%= escape_javascript(render(:partial => 'content')) %>");

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Note:</b>
  <%= @discussion.note_id %>
</p>

<p>
  <b>User:</b>
  <%= @discussion.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @discussion.content %>
</p>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>