config/routes.rb
Haokaigan::Application.routes.draw do
  
  resources :discussions

  resources :logs

  resources :tools

  root :to => 'home#index'
  
  resources :notifications

  resources :users

  resources :sessions,      :only => [:index, :new, :create, :destroy]

  get 'establishes/add'
  get 'home/caiwu'
  
  resources :experiences

  resources :partners

  resources :tips

  resources :pages

  resources :notes

  resources :chapters

  resources :establishes
  
  
  
  match '/admin/kuang' => 'admin#kuang'
  match '/admin/index' => 'admin#index'
  match '/admin/chapter' => 'admin#chapter'
  match '/admin/note' => 'admin#note'
  match '/admin/index/new' => 'establishes#new'
  match '/signout' => 'sessions#destroy'
  match '/signin' => 'sessions#new'
  
  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :establish
  has_many   :note
  has_many   :tip
  has_many   :partner
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/establish.rb
class Establish < ActiveRecord::Base
  has_many :chapter
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :chapter
  has_many :log, :dependent => :destroy
  has_many :user, :through => :log

  has_many :discussion, :dependent => :destroy
  has_many :user, :through => :discussion
    
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :chapter
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/setting.yml"
  namespace Rails.env
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :chapter
end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :notification, :dependent => :destroy
  has_many :log, :dependent => :destroy
  has_many :discussion, :dependent => :destroy


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password


  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate_name(name, submitted_password)
      user = find_by_name(name)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_email(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
  
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end


  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/admin/_form.html.erb
<p id="notice"><%= notice %></p>

<div id="admin_form">

<% @establish.each do |establish| %>

<span>	
	ID：<%= params[:id]+'- ' if !params[:id].nil?  %><%= establish.id %>  // Create：
	<%= link_to '单元', admin_index_new_path %> |
	<%= link_to '节', new_chapter_path(:id => params[:id]) %>	|
	<%= link_to '文章', new_note_path(:id => establish.id) %>	
</span> 

<%= form_for(establish) do |f| %>


<% if @chapter_s == true %>
<h1>编辑详细内容:  <%= link_to establish.name, admin_chapter_path(:id => establish.id) %></h1>
<% end %>

<% if @note_s == true %>
<h1>编辑详细内容:  <%= link_to establish.name, admin_note_path(:id => params[:id],:chapter => establish.id) %></h1>
<% end %>

  <% if establish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(establish.errors.count, "error") %> prohibited this establish from being saved:</h2>

      <ul>
      <% establish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,:rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% end %>

</div>

app/views/admin/_tool.html.erb
<div id="admin_tool">
	<li><p>当前位置：<%= @title %></p></li>
	<li><p>总共： <%= @establish.count %>条</p></li>
	<span>
		<li><%= link_to '后退',:back, :id => 'admin_tool_right' %></li>
	<span>
</div>

app/views/admin/chapter.html.erb
<%= render 'tool' %>

<% if @establish.count.to_i == 0 %>

<div id='admin_form'>
<span>	
	Create：
	<%= link_to '单元', admin_index_new_path %> |
	<%= link_to '节', new_chapter_path(:id => params[:id]) %>	|
	<%= link_to '文章', new_note_path(:id => params[:chapter])  %>	
</span> 
</div>

<% end %>

<%= render 'form' %>

app/views/admin/index.html.erb
<%= render 'tool' %>
<%= render 'form' %>

app/views/admin/kuang.html.erb
<h1>呈现页面</h1>
<li><%= link_to 'OBJECT','/establishes/1',:target => "admin_src" %></li>
<li><%= link_to 'EXPERIENCE','/experiences/',:target => "admin_src" %></li>
<li><%= link_to 'PAEES','/pages',:target => "admin_src" %></li>
<li><%= link_to 'ESTABLISHES','/establishes',:target => "admin_src" %></li>
<li><%= link_to 'TIPS','/tips',:target => "admin_src" %></li>
<li><%= link_to 'PARTNER','/partners',:target => "admin_src" %></li>

<h1>管理页面</h1>
<li><%= link_to 'ADMIN_CENTER','/admin/index',:target => "admin_src" %></li>
<li><%= link_to 'NEW ESTABLISH','/establishes/new',:target => "admin_src" %></li>
<li><%= link_to 'NEW EXPERIENCE','/experiences/new',:target => "admin_src" %></li>
<li><%= link_to 'NEW CHAPTER','/chapters/new',:target => "admin_src" %></li>
<li><%= link_to 'NEW NOTES','/notes/new',:target => "admin_src" %></li>
<li><%= link_to 'NEW TIPS','/tips/new',:target => "admin_src" %></li>
<li><%= link_to 'NEW PARTNER','/partners/new',:target => "admin_src" %></li>

app/views/admin/note.html.erb
<%= render 'tool' %>

<p id="notice"><%= notice %></p>

<div id="admin_form">

<% @establish.each do |establish| %>

<span>	
	ID：<%= params[:id] %> - <%= params[:chapter] %> - <%= establish.id %> // Create：
	<%= link_to '单元', admin_index_new_path %> |
	<%= link_to '节', new_chapter_path(:id => params[:id]) %>	|
	<%= link_to '文章', new_note_path(:id => params[:chapter]) %>	
</span>

<% if @chapter_s == true %>
<h1>编辑:  <%= link_to establish.name, admin_chapter_path(:id => establish.id) %></h1>
<% end %>

<% if @note_s == true %>
<h1>编辑:  <%= link_to establish.name, admin_note_path(:id => params[:id],:chapter => establish.id) %></h1>
<% end %>

<%= form_for(establish) do |f| %>
  <% if establish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(establish.errors.count, "error") %> prohibited this establish from being saved:</h2>

      <ul>
      <% establish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chapter_id %><br />
    <%= f.number_field :chapter_id %>
  </div>
  <div class="field">
    <%= f.label :que %><br />
    <%= f.text_field :que %>
  </div>
  <div class="field">
    <%= f.label :ans %><br />
    <%= f.text_area :ans,:rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<% end %>

</div>

app/views/shared/_footer.html.erb
<div id="blank">&nbsp;</div>

<div class="footer-wrap">
	<div id="footer-font"> 
	<% if signed_in? %>
	<%= link_to '全局日志', '/logs' %> | 
	<% end %>
	<%= Settings.copyright_name %></div>
	
</div>

app/views/shared/_header.html.erb
<div class="csNav"></div>
<div class="csGery">
		<%= link_to 'title', '/', :id => 'csLogo' %>
		<ul>
			<li>
				<%= link_to '首页', '/' %>
			</li>
			<li>
				<%= link_to '创业导航', establishes_path %>
			</li>
				<li>
					<%= link_to '工具箱', tools_path %>
				</li>
		</ul>


		<% if signed_in? %>
			<%= link_to '注销', signout_path, :id => 'csUser' %>
		<% else %>
			<%= link_to '登陆', signin_path, :id => 'csUser' %>
		<% end %>


			<% if signed_in? %>
			<%= link_to '欢迎回来，'+current_user.name, current_user, :id => 'csSession' %>
			<% else %>
			<span id="csUser">&nbsp;</span>
			<% end %>
</div>

app/views/shared/_message.html.erb
<% if !@noti.empty? %>

	<div class="ak">
	<div id="xbs" class="xv"> 
	
		<% @noti.each do |message| %> 
			<li><%= message.message %></li>
		<% end %>
	</div>
		
	<%= link_to '知道了', notification_path, :remote => true, :method => :delete, :id =>'xkr' %>
	</div>
<% end %>

app/views/shared/_sidebar.html.erb
	<div class="red"><span id="title_user_link"><%= @establish.name %></span></div>
	<% @chapter.each do |chapter| %>
	<div class="top"><%= link_to chapter.name,new_establish_path(:id => params[:id],:more => chapter.id), :remote => true, :id => "new_user_link", :class => "link" %></div>
	<% end %>