config/routes.rb
Haokaigan::Application.routes.draw do
  
  resources :discussions

  resources :logs

  resources :tools

  root :to => 'home#index'
  
  resources :notifications

  resources :users

  resources :sessions,      :only => [:index, :new, :create, :destroy]

  get 'establishes/add'
  get 'home/caiwu'
  
  resources :experiences

  resources :partners

  resources :tips

  resources :pages

  resources :notes

  resources :chapters

  resources :establishes
  
  
  
  match '/admin/kuang' => 'admin#kuang'
  match '/admin/index' => 'admin#index'
  match '/admin/chapter' => 'admin#chapter'
  match '/admin/note' => 'admin#note'
  match '/admin/index/new' => 'establishes#new'
  match '/signout' => 'sessions#destroy'
  match '/signin' => 'sessions#new'
  
  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :establish
  has_many   :note
  has_many   :tip
  has_many   :partner
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/establish.rb
class Establish < ActiveRecord::Base
  has_many :chapter
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :chapter
  has_many :log, :dependent => :destroy
  has_many :user, :through => :log

  has_many :discussion, :dependent => :destroy
  has_many :user, :through => :discussion
    
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :chapter
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/setting.yml"
  namespace Rails.env
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :chapter
end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :notification, :dependent => :destroy
  has_many :log, :dependent => :destroy
  has_many :discussion, :dependent => :destroy


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password


  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate_name(name, submitted_password)
      user = find_by_name(name)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_email(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
  
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end


  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = User.find(current_user.id).notification
    @notification.map(&:destroy)

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :unread %><br />
    <%= f.text_field :unread %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/destroy.js.erb
$('.ak').hide();

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th>Unread</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.user_id %></td>
    <td><%= notification.message %></td>
    <td><%= notification.unread %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @notification.user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @notification.message %>
</p>

<p>
  <b>Unread:</b>
  <%= @notification.unread %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>